package com.massivecraft.factions;

import java.util.ArrayList;
import java.util.EnumSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.entity.EntityType;

public class Conf {
   public static List<String> baseCommandAliases = new ArrayList<>();
   public static boolean allowNoSlashCommand = true;
   public static ChatColor colorMember = ChatColor.GREEN;
   public static ChatColor colorAlly = ChatColor.LIGHT_PURPLE;
   public static ChatColor colorNeutral = ChatColor.WHITE;
   public static ChatColor colorEnemy = ChatColor.RED;
   public static ChatColor colorPeaceful = ChatColor.GOLD;
   public static ChatColor colorWar = ChatColor.DARK_RED;
   public static ChatColor colorTrusted = ChatColor.BLUE;
   public static double powerPlayerMax = 10.0;
   public static double powerPlayerMin = -10.0;
   public static double powerPlayerStarting = 0.0;
   public static double powerPerMinute = 0.2;
   public static double powerPerDeath = 4.0;
   public static boolean powerRegenOffline = false;
   public static double powerOfflineLossPerDay = 0.0;
   public static double powerOfflineLossLimit = 0.0;
   public static double powerFactionMax = 0.0;
   public static String prefixAdmin = "**";
   public static String prefixMod = "*";
   public static int factionTagLengthMin = 3;
   public static int factionTagLengthMax = 10;
   public static boolean factionTagForceUpperCase = false;
   public static boolean newFactionsDefaultOpen = false;
   public static int factionMemberLimit = 0;
   public static String newPlayerStartingFactionID = "0";
   public static boolean showMapFactionKey = true;
   public static boolean showNeutralFactionsOnMap = true;
   public static boolean showEnemyFactionsOnMap = true;
   public static boolean canLeaveWithNegativePower = true;
   public static boolean factionOnlyChat = true;
   public static boolean chatTagEnabled = true;
   public static transient boolean chatTagHandledByAnotherPlugin = false;
   public static boolean chatTagRelationColored = true;
   public static String chatTagReplaceString = "[FACTION]";
   public static String chatTagInsertAfterString = "";
   public static String chatTagInsertBeforeString = "";
   public static int chatTagInsertIndex = 1;
   public static boolean chatTagPadBefore = false;
   public static boolean chatTagPadAfter = true;
   public static String chatTagFormat = "%s" + ChatColor.WHITE;
   public static String factionChatFormat = "%s:" + ChatColor.WHITE + " %s";
   public static String allianceChatFormat = ChatColor.LIGHT_PURPLE + "%s:" + ChatColor.WHITE + " %s";
   public static boolean broadcastDescriptionChanges = false;
   public static double autoLeaveAfterDaysOfInactivity = 10.0;
   public static double autoLeaveRoutineRunsEveryXMinutes = 5.0;
   public static boolean removePlayerDataWhenBanned = true;
   public static boolean worldGuardChecking = false;
   public static boolean worldGuardBuildPriority = false;
   public static boolean lwcIntegration = false;
   public static boolean onUnclaimResetLwcLocks = false;
   public static boolean onCaptureResetLwcLocks = false;
   public static boolean logFactionCreate = true;
   public static boolean logFactionDisband = true;
   public static boolean logFactionJoin = true;
   public static boolean logFactionKick = true;
   public static boolean logFactionLeave = true;
   public static boolean logLandClaims = true;
   public static boolean logLandUnclaims = true;
   public static boolean logMoneyTransactions = true;
   public static boolean logPlayerCommands = true;
   public static boolean handleExploitObsidianGenerators = true;
   public static boolean handleExploitEnderPearlClipping = true;
   public static boolean handleExploitInteractionSpam = true;
   public static boolean handleExploitTNTWaterlog = false;
   public static boolean homesEnabled = true;
   public static boolean homesMustBeInClaimedTerritory = true;
   public static boolean homesTeleportToOnDeath = true;
   public static boolean homesRespawnFromNoPowerLossWorlds = true;
   public static boolean homesTeleportCommandEnabled = true;
   public static boolean homesTeleportCommandEssentialsIntegration = true;
   public static boolean homesTeleportCommandSmokeEffectEnabled = true;
   public static float homesTeleportCommandSmokeEffectThickness = 3.0F;
   public static boolean homesTeleportAllowedFromEnemyTerritory = true;
   public static boolean homesTeleportAllowedFromDifferentWorld = true;
   public static double homesTeleportAllowedEnemyDistance = 32.0;
   public static boolean homesTeleportIgnoreEnemiesIfInOwnTerritory = true;
   public static boolean disablePVPBetweenNeutralFactions = false;
   public static boolean disablePVPForFactionlessPlayers = false;
   public static boolean enablePVPAgainstFactionlessInAttackersLand = false;
   public static int noPVPDamageToOthersForXSecondsAfterLogin = 3;
   public static boolean peacefulTerritoryDisablePVP = true;
   public static boolean peacefulTerritoryDisableMonsters = false;
   public static boolean peacefulMembersDisablePowerLoss = true;
   public static boolean permanentFactionsDisableLeaderPromotion = false;
   public static boolean claimsMustBeConnected = false;
   public static boolean claimsCanBeUnconnectedIfOwnedByOtherFaction = true;
   public static int claimsRequireMinFactionMembers = 1;
   public static int claimedLandsMax = 0;
   public static int radiusClaimFailureLimit = 9;
   public static double considerFactionsReallyOfflineAfterXMinutes = 0.0;
   public static int actionDeniedPainAmount = 1;
   public static Set<String> permanentFactionMemberDenyCommands = new LinkedHashSet<>();
   public static Set<String> territoryNeutralDenyCommands = new LinkedHashSet<>();
   public static Set<String> territoryEnemyDenyCommands = new LinkedHashSet<>();
   public static double territoryShieldFactor = 0.3;
   public static boolean territoryDenyBuild = true;
   public static boolean territoryDenyBuildWhenOffline = true;
   public static boolean territoryPainBuild = false;
   public static boolean territoryPainBuildWhenOffline = false;
   public static boolean territoryDenyUseage = true;
   public static boolean territoryEnemyDenyBuild = true;
   public static boolean territoryEnemyDenyBuildWhenOffline = true;
   public static boolean territoryEnemyPainBuild = false;
   public static boolean territoryEnemyPainBuildWhenOffline = false;
   public static boolean territoryEnemyDenyUseage = true;
   public static boolean territoryEnemyProtectMaterials = true;
   public static boolean territoryAllyDenyBuild = true;
   public static boolean territoryAllyDenyBuildWhenOffline = true;
   public static boolean territoryAllyPainBuild = false;
   public static boolean territoryAllyPainBuildWhenOffline = false;
   public static boolean territoryAllyDenyUseage = true;
   public static boolean territoryAllyProtectMaterials = true;
   public static boolean territoryBlockCreepers = false;
   public static boolean territoryBlockCreepersWhenOffline = false;
   public static boolean territoryBlockFireballs = false;
   public static boolean territoryBlockFireballsWhenOffline = false;
   public static boolean territoryBlockTNT = false;
   public static boolean territoryBlockTNTWhenOffline = false;
   public static boolean territoryDenyEndermanBlocks = true;
   public static boolean territoryDenyEndermanBlocksWhenOffline = true;
   public static boolean safeZoneDenyBuild = true;
   public static boolean safeZoneDenyUseage = true;
   public static boolean safeZoneBlockTNT = true;
   public static boolean safeZonePreventAllDamageToPlayers = false;
   public static boolean safeZoneDenyEndermanBlocks = true;
   public static boolean warZoneDenyBuild = true;
   public static boolean warZoneDenyUseage = true;
   public static boolean warZoneBlockCreepers = false;
   public static boolean warZoneBlockFireballs = false;
   public static boolean warZoneBlockTNT = true;
   public static boolean warZonePowerLoss = true;
   public static boolean warZoneFriendlyFire = false;
   public static boolean warZoneDenyEndermanBlocks = true;
   public static boolean wildernessDenyBuild = false;
   public static boolean wildernessDenyUseage = false;
   public static boolean wildernessBlockCreepers = false;
   public static boolean wildernessBlockFireballs = false;
   public static boolean wildernessBlockTNT = false;
   public static boolean wildernessPowerLoss = true;
   public static boolean wildernessDenyEndermanBlocks = false;
   public static boolean ownedAreasEnabled = true;
   public static int ownedAreasLimitPerFaction = 0;
   public static boolean ownedAreasModeratorsCanSet = false;
   public static boolean ownedAreaModeratorsBypass = true;
   public static boolean ownedAreaDenyBuild = true;
   public static boolean ownedAreaPainBuild = false;
   public static boolean ownedAreaProtectMaterials = true;
   public static boolean ownedAreaDenyUseage = true;
   public static String ownedLandMessage = "Owner(s): ";
   public static String publicLandMessage = "Public faction land.";
   public static boolean ownedMessageOnBorder = true;
   public static boolean ownedMessageInsideTerritory = true;
   public static boolean ownedMessageByChunk = false;
   public static boolean trustEnabled = true;
   public static boolean trustRequireAdmin = true;
   public static boolean trustDenyBuild = false;
   public static boolean trustProtectMaterials = false;
   public static boolean trustDenyUseage = false;
   public static boolean pistonProtectionThroughDenyBuild = true;
   public static Set<Material> territoryProtectedMaterials = EnumSet.noneOf(Material.class);
   public static Set<Material> territoryDenyUseageMaterials = EnumSet.noneOf(Material.class);
   public static Set<Material> territoryProtectedMaterialsWhenOffline = EnumSet.noneOf(Material.class);
   public static Set<Material> territoryDenyUseageMaterialsWhenOffline = EnumSet.noneOf(Material.class);
   public static transient Set<EntityType> safeZoneNerfedCreatureTypes = EnumSet.noneOf(EntityType.class);
   public static boolean spoutFactionTagsOverNames = true;
   public static boolean spoutFactionTitlesOverNames = true;
   public static boolean spoutFactionAdminCapes = true;
   public static boolean spoutFactionModeratorCapes = true;
   public static int spoutTerritoryDisplayPosition = 1;
   public static float spoutTerritoryDisplaySize = 1.0F;
   public static boolean spoutTerritoryDisplayShowDescription = true;
   public static boolean spoutTerritoryOwnersShow = true;
   public static boolean spoutTerritoryNoticeShow = true;
   public static int spoutTerritoryNoticeTop = 40;
   public static boolean spoutTerritoryNoticeShowDescription = false;
   public static float spoutTerritoryNoticeSize = 1.5F;
   public static float spoutTerritoryNoticeLeaveAfterSeconds = 2.0F;
   public static String capeAlly = "https://github.com/MassiveCraft/Factions/raw/master/capes/ally.png";
   public static String capeEnemy = "https://github.com/MassiveCraft/Factions/raw/master/capes/enemy.png";
   public static String capeMember = "https://github.com/MassiveCraft/Factions/raw/master/capes/member.png";
   public static String capeNeutral = "https://github.com/MassiveCraft/Factions/raw/master/capes/neutral.png";
   public static String capePeaceful = "https://github.com/MassiveCraft/Factions/raw/master/capes/peaceful.png";
   public static boolean econEnabled = false;
   public static String econUniverseAccount = "";
   public static double econCostClaimWilderness = 30.0;
   public static double econCostClaimFromFactionBonus = 30.0;
   public static double econClaimAdditionalMultiplier = 0.5;
   public static double econClaimRefundMultiplier = 0.7;
   public static double econClaimUnconnectedFee = 0.0;
   public static double econCostCreate = 100.0;
   public static double econCostOwner = 15.0;
   public static double econCostSethome = 30.0;
   public static double econCostJoin = 0.0;
   public static double econCostLeave = 0.0;
   public static double econCostKick = 0.0;
   public static double econCostInvite = 0.0;
   public static double econCostHome = 0.0;
   public static double econCostTag = 0.0;
   public static double econCostDesc = 0.0;
   public static double econCostTitle = 0.0;
   public static double econCostList = 0.0;
   public static double econCostMap = 0.0;
   public static double econCostPower = 0.0;
   public static double econCostShow = 0.0;
   public static double econCostOpen = 0.0;
   public static double econCostAlly = 0.0;
   public static double econCostEnemy = 0.0;
   public static double econCostNeutral = 0.0;
   public static double econCostNoBoom = 0.0;
   public static boolean bankEnabled = true;
   public static boolean bankMembersCanWithdraw = false;
   public static boolean bankFactionPaysCosts = true;
   public static boolean bankFactionPaysLandCosts = true;
   public static Set<String> playersWhoBypassAllProtection = new LinkedHashSet<>();
   public static Set<String> worldsNoClaiming = new LinkedHashSet<>();
   public static Set<String> worldsNoPowerLoss = new LinkedHashSet<>();
   public static Set<String> worldsIgnorePvP = new LinkedHashSet<>();
   public static Set<String> worldsNoWildernessProtection = new LinkedHashSet<>();
   public static transient int mapHeight = 8;
   public static transient int mapWidth = 39;
   public static transient char[] mapKeyChrs = "\\/#?$%=&^ABCDEFGHJKLMNOPQRSTUVWXYZ1234567890abcdeghjmnopqrsuvwxyz".toCharArray();
   private static transient Conf i = new Conf();

   static {
      baseCommandAliases.add("f");
      territoryEnemyDenyCommands.add("home");
      territoryEnemyDenyCommands.add("sethome");
      territoryEnemyDenyCommands.add("spawn");
      territoryEnemyDenyCommands.add("tpahere");
      territoryEnemyDenyCommands.add("tpaccept");
      territoryEnemyDenyCommands.add("tpa");
      territoryProtectedMaterials.add(Material.OAK_DOOR);
      territoryProtectedMaterials.add(Material.OAK_TRAPDOOR);
      territoryProtectedMaterials.add(Material.OAK_FENCE_GATE);
      territoryProtectedMaterials.add(Material.DISPENSER);
      territoryProtectedMaterials.add(Material.CHEST);
      territoryProtectedMaterials.add(Material.FURNACE);
      territoryProtectedMaterials.add(Material.REPEATER);
      territoryProtectedMaterials.add(Material.JUKEBOX);
      territoryProtectedMaterials.add(Material.BREWING_STAND);
      territoryProtectedMaterials.add(Material.ENCHANTING_TABLE);
      territoryProtectedMaterials.add(Material.CAULDRON);
      territoryProtectedMaterials.add(Material.FARMLAND);
      territoryProtectedMaterials.add(Material.BEACON);
      territoryProtectedMaterials.add(Material.ANVIL);
      territoryDenyUseageMaterials.add(Material.FIRE_CHARGE);
      territoryDenyUseageMaterials.add(Material.FLINT_AND_STEEL);
      territoryDenyUseageMaterials.add(Material.BUCKET);
      territoryDenyUseageMaterials.add(Material.WATER_BUCKET);
      territoryDenyUseageMaterials.add(Material.LAVA_BUCKET);
      territoryProtectedMaterialsWhenOffline.add(Material.OAK_DOOR);
      territoryProtectedMaterialsWhenOffline.add(Material.OAK_TRAPDOOR);
      territoryProtectedMaterialsWhenOffline.add(Material.OAK_FENCE_GATE);
      territoryProtectedMaterialsWhenOffline.add(Material.DISPENSER);
      territoryProtectedMaterialsWhenOffline.add(Material.CHEST);
      territoryProtectedMaterialsWhenOffline.add(Material.FURNACE);
      territoryProtectedMaterialsWhenOffline.add(Material.REPEATER);
      territoryProtectedMaterialsWhenOffline.add(Material.JUKEBOX);
      territoryProtectedMaterialsWhenOffline.add(Material.BREWING_STAND);
      territoryProtectedMaterialsWhenOffline.add(Material.ENCHANTING_TABLE);
      territoryProtectedMaterialsWhenOffline.add(Material.CAULDRON);
      territoryProtectedMaterialsWhenOffline.add(Material.FARMLAND);
      territoryProtectedMaterialsWhenOffline.add(Material.BEACON);
      territoryProtectedMaterialsWhenOffline.add(Material.ANVIL);
      territoryDenyUseageMaterialsWhenOffline.add(Material.FIRE_CHARGE);
      territoryDenyUseageMaterialsWhenOffline.add(Material.FLINT_AND_STEEL);
      territoryDenyUseageMaterialsWhenOffline.add(Material.BUCKET);
      territoryDenyUseageMaterialsWhenOffline.add(Material.WATER_BUCKET);
      territoryDenyUseageMaterialsWhenOffline.add(Material.LAVA_BUCKET);
      safeZoneNerfedCreatureTypes.add(EntityType.BLAZE);
      safeZoneNerfedCreatureTypes.add(EntityType.CAVE_SPIDER);
      safeZoneNerfedCreatureTypes.add(EntityType.CREEPER);
      safeZoneNerfedCreatureTypes.add(EntityType.ENDER_DRAGON);
      safeZoneNerfedCreatureTypes.add(EntityType.ENDERMAN);
      safeZoneNerfedCreatureTypes.add(EntityType.GHAST);
      safeZoneNerfedCreatureTypes.add(EntityType.MAGMA_CUBE);
      safeZoneNerfedCreatureTypes.add(EntityType.ZOMBIFIED_PIGLIN);
      safeZoneNerfedCreatureTypes.add(EntityType.SILVERFISH);
      safeZoneNerfedCreatureTypes.add(EntityType.SKELETON);
      safeZoneNerfedCreatureTypes.add(EntityType.SPIDER);
      safeZoneNerfedCreatureTypes.add(EntityType.SLIME);
      safeZoneNerfedCreatureTypes.add(EntityType.WITCH);
      safeZoneNerfedCreatureTypes.add(EntityType.WITHER);
      safeZoneNerfedCreatureTypes.add(EntityType.ZOMBIE);
   }

   public static void load() {
      P.p.persist.loadOrSaveDefault(i, Conf.class, "conf");
   }

   public static void save() {
      P.p.persist.save(i);
   }
}
